apiVersion: extensions/v1beta1
kind: Ingress
metadata:
    name: ingress-service
    annotations:
        kubernetes.io/ingress.class: nginx
        # nginx.ingress.kubernetes.io/rewrite-target: /
        nginx.ingress.kubernetes.io/proxy-body-size: "20m"
        nginx.ingress.kubernetes.io/proxy-read-timeout: "7200"
        nginx.ingress.kubernetes.io/proxy-send-timeout: "7200"
        kubernetes.io/tls-acme: 'true'
spec:
    rules:
      - http:
          paths:
            - path: /
              backend:
                  serviceName: ui-app-cluster-ip-service
                  servicePort: 80
            - path: /read/
              backend:
                  serviceName: read-server-cluster-ip-service
                  servicePort: 60000
            - path: /write/
              backend:
                  serviceName: write-server-cluster-ip-service
                  servicePort: 50000