apiVersion: apps/v1
kind: Deployment
metadata:
    name: write-server-deployment
spec:
    replicas: 1
    selector:
        matchLabels:
          component: backend-write-server
    template:
        metadata:
            labels:
                component: backend-write-server
        spec:
            containers:
              - name: write-server
                #image: sifarone/eod_analysis:write-server-3.0
                image: sifarone/k8s_write_server
                ports:
                    - containerPort: 50000
                env:
                  - name: MONGODB_HOST
                    value: mongodb-cluster-ip-service
                  - name: MONGODB_PORT
                    value: '27017'
                  - name: REDIS_HOST
                    value: redis-cluster-ip-service
                  - name: REDIS_PORT
                    value: '6379'
                  - name: WRITE_SERVER_HOST
                    value: '0.0.0.0'
                  - name: WRITE_SERVER_PORT
                    value: '50000'

            imagePullSecrets:
              - name: regcred
